apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: exec
  name: 'syncrator-api-qas'
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      git-branch: master
    labels:
      ENV: ${ENV}
      app: 'syncrator-api'
      component: frontend
    name: 'syncrator-api-${ENV}'
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      ENV: ${ENV}
      app: 'syncrator-api'
      type: 'exec'
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      git-branch: master
    generation: 1
    labels:
      ENV: ${ENV}
      app: 'syncrator-api'
      type: 'exec'
    name: 'syncrator-api-${ENV}'
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      ENV: ${ENV}
      app: 'syncrator-api'
      type: 'exec'
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          git-branch: master
        labels:
          ENV: ${ENV}
          app: 'syncrator-api'
          type: 'exec'
      spec:
        containers:
        - env:
          - name: some_var
            value: some_key
          image: docker-registry.default.svc:5000/viaa-tools/syncrator-api
          imagePullPolicy: IfNotPresent
          
          name: 'syncrator-api'
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: '${cpu_limit}m'
              memory: '${memory_limit}Mi'
            requests:
              cpu: '${cpu_requested}m'
              memory: '${memory_requested}Mi'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 101
        terminationGracePeriodSeconds: 10
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - 'syncrator-api'
        from:
          kind: ImageStreamTag
          name: 'syncrator-api:${ENV}'
          namespace: 'viaa-tools'
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
  - name: ENV
    value: 'qas'
  - name: 'memory_requested'
    value: '128'
  - name: 'memory_limit'
    value: '328'
  - name: 'cpu_requested'
    value: '100'
  - name: 'cpu_limit'
    value: '300'