apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: syncrator
  template: init
  env: global
objects:
- apiVersion: v1
  kind: ConfigMap
  labels:
    env: global
  metadata:
    name: syncrator-global
  data:
    PRODUCER: mam
    RUBY_ENV: production
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: syncrator-target-metadatacatalogus
  data:
    TARGET_DATASTORE: solr_pids
    MAM_VERSION: '1'
    MAM_USER: ${CATALOGI_MAM_USER}
    MAM_PASSWORD: ${CATALOGI_MAM_PASSWORD}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: syncrator-target-cataloguspro
  data:
    TARGET_DATASTORE: solr_pids
    MAM_VERSION: '1'
    MAM_USER: ${CATALOGI_MAM_USER}
    MAM_PASSWORD: ${CATALOGI_MAM_PASSWORD}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: syncrator-target-avo
  data:
    TARGET_DATASTORE: postgresql
    MAM_VERSION: '2'
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: syncrator
    namespace: shared-components
  spec:
    lookupPolicy:
      local: true
    tags:
      - from:
          kind: DockerImage
          name: registry.gitlab.com/viaa-catalogus/syncrator/qas:latest
        importPolicy:
          scheduled: true
        name: latest
      - from:
          kind: DockerImage
          name: registry.gitlab.com/viaa-catalogus/syncrator/master:latest
        importPolicy:
          scheduled: true
        name: stable
parameters:
- description: CATALOGI_MAM_USER
  displayName: CATALOGI_MAM_USER
  name: CATALOGI_MAM_USER
  required: true
- description: CATALOGI_MAM_PASSWORD
  displayName: CATALOGI_MAM_PASSWORD
  name: CATALOGI_MAM_PASSWORD
  required: true
