apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: syncrator
  env: ${ENV}
  target: ${TARGET}
  action_name: ${ACTION_NAME}
  template: job
metadata:
  name: syncrator-job
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: syncrator-${ENV}-${TARGET}-${ACTION_NAME}
  spec:
    template:
      spec:
        containers:
          - name: syncrator-${ENV}-${TARGET}-${ACTION_NAME}
            image: syncrator:${IS_TAG}
            command: ["/bin/bash", "-c", "cd /usr/local/bundle/gems/syncrator*;rake db:migrate;syncrator ${ACTION} ${OPTIONS}"]
            env:
              - name: MAM_MAIN_QUERY
                value: ${MAM_MAIN_QUERY}
            envFrom:
              - configMapRef:
                  name: syncrator-envtarget-${ENV}-${TARGET}
        restartPolicy: Never
parameters:
- description: Environment, used to id job and config map, e.g. 'qas' or 'prd'
  displayname: ENV
  name: ENV
  required: true
- description: TARGET, e.g. catalogus/metadatacatalogus/avo, used to id job and config map, can be arbitrary
  displayname: TARGET
  name: TARGET
  required: true
- description: ACTION_NAME, used to id job, e.g. sync/sync_cp_vrt
  displayname: ACTION_NAME
  name: ACTION_NAME
  required: true
- description: ACTION, syncrator command e.g. sync/delta/delete
  displayname: ACTION
  name: ACTION
  required: true
- description: OPTIONS, syncrator command options e.g. --debug/-n 1000 -c 1
  displayname: OPTIONS
  name: OPTIONS
  required: true
- description: IS_TAG, Image stream tag, e.g. latest/stable
  displayname: IS_TAG
  name: IS_TAG
  required: true
  value: stable
- description: MAM_MAIN_QUERY, optional replacement query for sync command
  displayname: MAM_MAIN_QUERY
  name: MAM_MAIN_QUERY
