apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "syncrator-api"
  labels:
    app: "syncrator-api"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "syncrator-api-${env}"
      namespace: "etl"
      labels:
        app: "syncrator-api"
        app.kubernetes.io/component: "syncrator-api-${env}"
        app.kubernetes.io/instance: "syncrator-api-${env}"
        app.kubernetes.io/name: "syncrator-api"
        app.kubernetes.io/part-of: "syncrator-api"
        app.openshift.io/runtime: "syncrator-api"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "syncrator-api-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "syncrator-api-${env}"
      namespace: "etl"
      labels:
        app: "syncrator-api"
        app.kubernetes.io/component: "syncrator-api-${env}"
        app.kubernetes.io/instance: "syncrator-api-${env}"
        app.kubernetes.io/name: "syncrator-api"
        app.kubernetes.io/part-of: "syncrator-api"
        app.openshift.io/runtime: "syncrator-api"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "syncrator-api-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "syncrator-api-${env}"
            deploymentconfig: "syncrator-api-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "syncrator-api-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "syncrator-api-${env}"
                - secretRef:
                    name: "syncrator-api-${env}"
                - secretRef:
                    name: syncrator-api-open-shift-auth
              image: >-
                image-registry.openshift-image-registry.svc:5000/etl/syncrator-api:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "syncrator-api-${env}"
      namespace: "etl"
      labels:
        app: "syncrator-api"
        app.kubernetes.io/component: "syncrator-api-${env}"
        app.kubernetes.io/instance: "syncrator-api-${env}"
        app.kubernetes.io/name: "syncrator-api"
        app.kubernetes.io/part-of: "syncrator-api"
        app.openshift.io/runtime: "syncrator-api"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      OC_PROJECT_NAME: some_value
      OAS_SERVER: some_value
      OAS_APPNAME: some_value
      SYNC_ENV: "${env}"
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "syncrator-api-${env}"
      namespace: "etl"
      labels:
        app: "syncrator-api"
        app.kubernetes.io/component: "syncrator-api-${env}"
        app.kubernetes.io/instance: "syncrator-api-${env}"
        app.kubernetes.io/name: "syncrator-api"
        app.kubernetes.io/part-of: "syncrator-api"
        app.openshift.io/runtime: "syncrator-api"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      DATABASE_URL: ''
      OAS_JWT_SECRET: ''
  - kind: Secret
    apiVersion: v1
    metadata:
      name: syncrator-api-open-shift-auth
      namespace: etl
      labels:
        app: syncrator-api
        app.kubernetes.io/component: syncrator-api
        app.kubernetes.io/instance: syncrator-api
        app.kubernetes.io/name: syncrator-api
        app.kubernetes.io/part-of: syncrator-api
        app.openshift.io/runtime: syncrator-api
    stringData:
      OC_URL: ''
      OC_SERVICE_ACCOUNT_TOKEN: ''
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"